server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerservice
          uri: lb://customerservice
          predicates:
            - Path=/customers/**
        - id: creditservice
          uri: lb://creditservice
          predicates:
            - Path=/credits/**
        - id: accountservice
          uri: lb://accountservice
          predicates:
            - Path=/accounts/**